nick = User.create(username: "nnobile", email: "nickcnobile@gmail.com", password: "guadalupe")
jerome = User.create(username: "jbillings", email: "jbillings@gmail.com", password: "hidalgo")
jordan = User.create(username: "mjordan", email: "michael@jordan.com", password: "jumpman23")
austin = User.create(username: "awalker", email: "awalker@yahoo.com", password: "skywalker33")

Sneaker.create(brand: "Nike", model: "Air Max 97", price: 102.38, sport: "lifestyle", size: 11, user_id: nick.id)
Sneaker.create(brand: "Onitsuka Tiger", model: "Ultimate 81", price: 74.95, sport: "running", size: 11, user_id: nick.id)
Sneaker.create(brand: "New Balance", model: "Made in UK 991", price: 225, sport: "lifestyle", size: 11, user_id: nick.id)
Sneaker.create(brand: "Adidas", model: "Pro Bounce", price: 60, sport: "basketball", size: 14.5, user_id: jerome.id)
Sneaker.create(brand: "Fila", model: "Axilus 2", price: 110, sport: "tennis", size: 14, user_id: jerome.id)
Sneaker.create(brand: "Nike", model: "Jordan 1", price: 115, sport: "basketball", size: 13, user_id: jordan.id)
Sneaker.create(brand: "Nike", model: "Air Jordan 13 Retro", price: 109, sport: "basketball", size: 13, user_id: jordan.id)
Sneaker.create(brand: "Nike", model: "Zoom Trunner Ultimate", price: 150, sport: "running", size: 13, user_id: jordan.id)
Sneaker.create(brand: "Nike", model: "ADG 2", price: 150, sport: "golf", size: 13, user_id: jordan.id)
Sneaker.create(brand: "Vans", model: "Sk8 High", price: 65, sport: "skateboarding", size: 9.5, user_id: austin.id)
Sneaker.create(brand: "Nike", model: "SB Shane", price: 80, sport: "skateboarding", size: 9.5, user_id: austin.id)
Sneaker.create(brand: "Saucony", model: "Guide 13", price: 120, sport: "running", size: 9.5, user_id: austin.id)
